development:
  adapter: mysql2
  pool: 5
  username: "root"
  password: 1234
  host: localhost
  port: 3306
  database: 'bank'
test:
  adapter: mysql2
  database: bank
  username: root
  password: 1234
  host: localhost
production:
  adapter: mysql2
  pool: 5
  username: "bank"
  password: "NQY4bbKV7GLDpFSq"
  host: "188.226.172.162"
  port: 3306
  database: 'bank'
