default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

development:
  adapter: mysql2
  pool: 5
  username: "bank"
  password: "NQY4bbKV7GLDpFSq"
  host: "188.226.172.162"
  port: 3306
  database: 'bank'