# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7805e6a5f438c905eb68812598f14e9289da25924d82eb5658dfe3738c8d806540b8f169d71305909df965de852615107f157e5c09b15b17ebc0aa1b06a78d42

test:
  secret_key_base: d34a66e8604895bbb6b52bd8cbd40d05778b0217b101d6051b09dd287d280f131d464cc63d5a05334f48424aa78dfb14d20dd1d957722668e7d5f819eb6ae6fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
